src/components/UnauthorizedUserComponents/MainPageComponents/AuthSection/AuthSection.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/AuthSection/AuthSection.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/Description/Description.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/Description/Description.styled.jsx
add description section, mobile version
=> add Description

src/components/PageLayout/PageLayout.jsx, src/components/PageLayout/PageLayout.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.styled.jsx, src/pages/AccountPage/AccountPage.jsx, src/pages/CalendarPage/CalendarPage.jsx, src/pages/LoginPage/LoginPage.jsx, src/pages/MainPage/MainPage.jsx, src/pages/RegisterPage/RegisterPage.jsx, src/pages/StatisticsPage/StatisticsPage.jsx
Катя, привіт. Створила компонент PageLayout, в якому зафіксувала розміри сторінки для різних екранів та додала падінги. Обгорнула ним КОЖНУ сторінку, передивись, плз. Також у Олени трішки зайвих падингів, бо вона їх заклала у себе в коді.
=> PageLayout

src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.jsx, src/components/AuthorizedUserComponents/Header/HeaderItems/AddFeedbackBtn.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/TaskForm.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/TaskForm.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.jsx
Катя, привіт! Закінчила верстку TaskModal, додала до неї валідацію через YUP, логіку збирання даних з форми
=> TaskModalValidation

src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbar.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbar.styled.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.styled.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodTypeSelect.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodTypeSelect.styled.jsx, src/components/PageLayout/PageLayout.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/AuthSection/AuthSection.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.styled.jsx, src/pages/MainPage/MainPage.jsx
add calendar toolbar styles, corrected styles for Unauthorized Components
=> add calendar toolbar

src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbar.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodTypeSelect.jsx
add pagination, changing period day/month
=> add CalendarToollbar logic

src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenMonth/ChosenMonthItem/CalendarTable.jsx
тут все вкупі, потім розкидаємо, щоб можна було з цим далі працювати
=> add calendar

src/components/AuthorizedUserComponents/SideBar/SideBar.jsx, src/components/UnauthorizedUserComponents/LoginPageComponents/LoginForm/LoginForm.jsx, src/components/UnauthorizedUserComponents/RegisterPageComponents/RegisterForm/RegisterForm.jsx, src/store/auth/authOperations.js, src/store/auth/authSlice.js
=> add validation signup

src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.styled.jsx, src/components/UnauthorizedUserComponents/LoginPageComponents/LoginForm/LoginForm.jsx, src/components/UnauthorizedUserComponents/LoginPageComponents/LoginForm/LoginForm.styled.jsx, src/components/UnauthorizedUserComponents/RegisterPageComponents/RegisterForm/RegisterForm.jsx
added DataPicker without styles, added home icon to Login and Register
=> add DataPicker

src/components/AuthorizedUserComponents/SideBar/SideBar.jsx, src/components/UnauthorizedUserComponents/LoginPageComponents/LoginForm/LoginForm.jsx, src/components/UnauthorizedUserComponents/RegisterPageComponents/RegisterForm/RegisterForm.jsx, src/store/auth/authOperations.js
=> add logout

src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.jsx, src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.styled.jsx, src/components/AuthorizedUserComponents/Header/HeaderItems/AddFeedbackBtn.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/TaskForm.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.jsx, src/pages/MainPage/MainPage.jsx, src/store/feedback/feedbackSlice.js, src/store/feedback/feedbackThunks.js
Додала реальні дані на слайдер
=> Added reviews to slider from back-end

src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/AddTaskBtn.jsx, src/components/AuthorizedUserComponents/Header/HeaderItems/AddFeedbackBtn.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/TaskForm.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.jsx, src/store/tasks/tasksSlice.js, src/store/tasks/tasksThunks.js
=> Add task - done

src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.styled.jsx
add styles, need to improve them, will do it at night
=> add styles to DatePicker

src/components/AuthorizedUserComponents/AccountPageComponents/UserForm/UserForm.jsx, src/helpers/instance.js, src/store/user/operations.js
Пофіксив додавання фото та додав динамічний токен, а також додав додавання Аксес токену до локалсторідж при логіні (там один рядок в хелперсах)
=> update add photo and others

src/components/UnauthorizedUserComponents/LoginPageComponents/AuthField/AuthField.jsx, src/components/UnauthorizedUserComponents/LoginPageComponents/AuthField/AuthField.styled.jsx, src/components/UnauthorizedUserComponents/RegisterPageComponents/RegisterForm/RegisterForm.jsx, src/store/auth/authOperations.js
=> add visible pass

src/components/AuthorizedUserComponents/CalendarPageComponents/CalendarToolbar/CalendarToolbarItems/PeriodPaginator.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.jsx
fixed datePicker styles, added loader to reviews
=> fix datePicker styles

src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/ColumnHeadBar.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/TaskToolbar.jsx, src/components/CommonComponents/TaskModal/TaskModal.jsx, src/components/GeneralComponents/Overlay/Overlay.styled.jsx
Пофіксила Add btn на плюсику, додала модалку до Delete task
=> Added modal for delete task and fixed Add task btn

src/components/AuthorizedUserComponents/AccountPageComponents/UserForm/UserForm.jsx, src/components/AuthorizedUserComponents/AccountPageComponents/UserForm/UserForm.styled.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDay.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDay.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/AuthSection/AuthSection.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.styled.jsx
=> add Loader

src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/TaskToolbar.jsx
Додала можливість переміщати таски по кліку
=> Added popover to move tasks

src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/AddTaskBtnStyle.js, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/TaskToolbar.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/Modal.styled.jsx, src/components/GeneralComponents/ModalButton/ModalButton.styled.jsx, src/components/GeneralComponents/ModalWindow/ModalWindow.styled.jsx, src/components/UnauthorizedUserComponents/MainPageComponents/ReviewsSlider/ReviewsSlider.styled.jsx
disable to edit review and scale for arrow
=> disable to edit review

src/components/AuthorizedUserComponents/AddFeedbackModal/FeedbackForm.jsx, src/components/AuthorizedUserComponents/CalendarPageComponents/ChosenDay/ChosenDayItems/TasksColumnItems/TaskToolbar.jsx, src/components/CommonComponents/TaskModal/TaskModal.jsx, src/components/CommonComponents/TaskModal/TaskModalItems/TaskForm.jsx, src/helpers/toastNotification.js, src/store/feedback/feedbackSlice.js, src/store/store.js, src/store/tasks/tasksSlice.js
added notification like middleware
=> added notification like middleware
